repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --fix
        language: system
        types: [python]
        require_serial: true
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
