study:
  id: trust_survival_v29_intent
  title: Trust_Survival_Phase29_IntentRealignment
name: "Trust_Survival_Phase29_IntentRealignment"
extends: "studies/trust_survival/study.yml"
description: |
  Phase 29 introduces a persistent Intent variable I(t) capturing preferred state trajectories
  (CCI↑, Survival↑, Hazard↓) inferred from reflective summaries. The system learns to minimize
  divergence between I(t) and current metrics while preserving safety and metastable flexibility.
objectives:
  - Show stable intent formation (low volatility, high persistence).
  - Reduce alignment error (I vs. state) with short lag and no safety regressions.
  - Demonstrate positive utility gain vs. P28 reflective baseline.
design:
  seeds: 6
  epochs_cap: 2000
  agents: 960
  clusters: 36
  factors:
    domain: ["cultural","economic","ecological"]
    mode: ["ARC_TAF_RIL","ARC_TAF_INTENT"]
    hierarchy: ["three_layer"]
    inter_kappa: [0.18]
    inter_delay: [25]
    shock_cadence: ["baseline"]
    shock_severity: [0.35]
    goal_inequality: [0.35]
intent:
  enabled: true
  components: ["CCI","Survival","Hazard"]
  init: { CCI: 0.80, Survival: 0.86, Hazard: 0.40 }
  ema_persistence: 0.94
  max_drift: { CCI: 0.02, Survival: 0.02, Hazard: 0.02 }
  learning_rate: 0.15
  alignment:
    k_intent: { CCI: 0.20, Survival: 0.25, Hazard: -0.18 }
    eps_nudge_max: 0.05
    lr_nudge_max: 0.06
  guards:
    hazard_max: 0.47
    survival_min: 0.80
    cci_floor: 0.72
arc_controller:
  window: 60
  targets: { CCI: 0.72, survival: 0.80, hazard_soft: 0.47 }
  gains: { k_survival: 0.60, k_hazard: -0.25, k_integral: 0.10 }
  momentum_tune: { base: 0.10, sync_gain: 1.25, desync_div: 0.85, k_coherence: 0.25, k_vol: -0.20 }
  bounds: { lr_min: 0.006, lr_max: 0.16, m_min: 0.00, m_max: 0.35 }
  soft_guards: { hazard_uplift_max: 0.05, ramp_gamma: 0.96 }
resonance:
  amplitude: 0.12
  period_T: 100
  phase_phi: 0.0
  eps_min: 0.05
  eps_max: 0.80
  pulse: { every: 100, eps_delta: 0.06, lr_boost: 1.10 }
containment:
  enabled: true
  trigger: { hazard_lo: 0.45, hazard_hi: 0.50, var_hi: 0.03 }
  absorption: { alpha: 0.35, max_rate: 0.08 }
  reservoir: { cap: 1.80 }
reinjection_adaptive:
  enabled: true
  min_delay: 25
  ema_smoothing: 0.80
  gate: { hazard_max: 0.47, cci_min: 0.72 }
  neighborhood: { kappa_bias: 0.6, deficit_floor: 0.05 }
  schedule: { base_beta: 0.14, burst_bonus: 1.20, taper_gamma: 0.94 }
  effects: { eps_delta_scale: 0.06, lr_boost_scale: 0.08 }
taf:
  enabled: true
  momentum_window: 30
  smoothing: 0.85
  gain: { base: 1.0, k_sync: 0.25, k_hazard_brake: -0.40, max_gain: 1.8, min_gain: 0.7 }
  limiter: { lookback: 80, slope_max: 0.08, cooldown: 40 }
  routing: { top_k: 3, spillover: 0.15 }
metrics:
  - survival_rate
  - hazard
  - collapse_risk
  - CCI
  - inter_sync_index
  - lr_trust_mean
  - momentum_mean
  - openness_eps_mean
  - taf_gain_mean
  - taf_focus_score
  - prediction_accuracy
  - self_model_consistency
  - intent_magnitude
  - intent_volatility
  - intent_persistence
  - intent_alignment_error
  - alignment_lag
  - goal_drift_rate
  - utility_gain
  - safety_hold_ratio
integrity:
  code_freeze: true
  bootstrap_resamples: 480
  blinded: true
  null_test: true
  thresholds:
    cci: 0.72
    survival: 0.80
validation:
  pass_if:
    - "ARC_TAF_INTENT vs ARC_TAF_RIL: utility_gain ≥ +0.05 (95% CI excludes 0)"
    - "intent_persistence ≥ 0.90 and intent_volatility ≤ 0.12"
    - "median intent_alignment_error reduced by ≥ 20% vs baseline"
    - "alignment_lag ≤ 60 epochs (95% CI)"
    - "safety_hold_ratio ≥ 0.90 and mean hazard ≤ 0.47; collapse risk ≈ 0"
exports:
  data_dir: discovery_results/trust_survival_v29/data
  figs_dir: discovery_results/trust_survival_v29/figs
  report_dir: discovery_results/trust_survival_v29/report
  bundle_zip: discovery_results/trust_survival_v29/bundle.zip
adapter:
  path: "studies/trust_survival/adapter_trust_intent.py"
  entrypoint: "run_study"
notes:
  prereg: true
  comment: "Phase 29: Intent formation & realignment atop reflective controller."
prereg:
  constants:
    epochs: 2000
    seeds: [2901,2902,2903,2904,2905,2906]
    agents: [960]
    clusters: [36]
    domain: ["cultural","economic","ecological"]
    mode: ["ARC_TAF_RIL","ARC_TAF_INTENT"]
    hierarchy: ["three_layer"]
    sim_adapter: "studies/trust_survival/adapter_trust_intent.py:run"
