include: configs/base.yaml
experiment: param_sweep
sweep_param: goal_inequality
values: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.8]
fixed:
  shock_level: 0.40
  coordination_strength: 0.60
out_csv: reslab/exports/ineq_ramp.csv
out_fig: reslab/exports/ineq_ramp.png
label: "Goal Inequality → Survival/Alignment (shock=0.40, coord=0.60)"


