include: configs/base.yaml
experiment: param_sweep
sweep_param: noise
values: [0.0, 0.1, 0.2, 0.4, 0.6, 0.8, 1.0]  # More extreme noise values
out_csv: reslab/results/noise_sweep.csv
out_fig: reslab/results/noise_sweep.png
