include: configs/base.yaml
experiment: grid
grid:
  coordination_strength: [0.4, 0.5, 0.6, 0.7, 0.8]
  goal_inequality: [0.1, 0.2, 0.3, 0.4, 0.5]
fixed:
  shock_level: 0.50   # transition edge
out_csv: reslab/exports/stability_grid.csv
out_fig: reslab/exports/stability_grid.png
label: "Stability Grid @ shock=0.50 (heatmap)"


