name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python -m pip install -U pip
      - run: pip install -r requirements.txt
      - run: pip install black ruff pytest
      - run: ruff check .
      - run: black --check .
      - run: pytest -q
  guardian:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - run: python qc/guardian_v4/guardian_v4.py --corpus --fail-under 85

